# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSmokeTest():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminpage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
    self.driver.set_window_size(1426, 848)
    # Make sure the "Username" input box is present
    username_element = self.driver.find_element(By.ID, "username")
    assert username_element is not None
    # Fill in an incorrect username and password
    username_element.click()
    username_element.send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("wrongpassword")
    # Click the Login button
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    # Ensure the appropriate error message is displayed
    error_elements = self.driver.find_elements(By.XPATH, "//*[contains(text(), 'Invalid') or contains(text(), 'incorrect') or contains(text(), 'error') or contains(text(), 'wrong')]")
    assert len(error_elements) > 0
  
  def test_directorypage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
    self.driver.set_window_size(1498, 848)
    # Click on the "Grid" button to display the card view
    self.driver.find_element(By.ID, "directory-grid").click()
    # Make sure that the "Teton Turf and Tree" business is shown in the cards
    elements = self.driver.find_elements(By.XPATH, "//*[contains(text(), 'Teton Turf and Tree')]")
    assert len(elements) > 0
    # Click on the "List" button to display the list view
    self.driver.find_element(By.ID, "directory-list").click()
    # Again, make sure that the "Teton Turf and Tree" business is displayed in the list
    elements = self.driver.find_elements(By.XPATH, "//*[contains(text(), 'Teton Turf and Tree')]")
    assert len(elements) > 0
  
  def test_homepage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1417, 848)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 > .centered-image")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 > .centered-image")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us!")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us!").click()
  
  def test_joinpage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
    self.driver.set_window_size(1382, 848)
    # Make sure the "First Name" input box is present
    first_name_element = self.driver.find_element(By.NAME, "fname")
    assert first_name_element is not None
    # Fill in the first page with information of your choosing
    first_name_element.click()
    first_name_element.send_keys("ivan")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("sembatya")
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("ivaste youth talents")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").send_keys("engineer")
    # Click the "Next Step" button
    self.driver.find_element(By.NAME, "submit").click()
    # Make sure the "Email" input box is present
    email_element = self.driver.find_element(By.NAME, "email")
    assert email_element is not None
  
